### ISSUE TITLE
Termina el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-carmenpmoreno#1]
Buen trabajo @carmenpmoreno 

Algunas pistas para acabarlo:

- [x] Termina de añadir los componentes finales: recuerda que **PokeList** suele contener la lista de elementos y **Pokemon** tendrá solo la tarjeta
- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by carmenpmoreno** [comment]
Gracias @nasivuela ! Ya he terminado el ejercicio :) Ya me dirás si todo está correcto.
Besos!

**Comment by nasivuela** [comment]
Bien hecho @carmenpmoreno !!

Revisa los punto que he desmarcado, que aun necesitan algo de trabajo, y mira este otro

- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`


Cuando tengas esto cerramos el issue, pero si quieres continuar puedes:

- Añadir una página de detalle por cada Pokemon.

- Añadir la posibilidad de marcar favoritos con estos pasos:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by carmenpmoreno** [comment]
Gracias @nasivuela ! He hecho lo q me comentas en cada tarjeta... .Los tips de la anterior issue desmarcados los marqué al verlos así, pensando que fueron despiste mío...al leer tu mensaje veo que los desmarcaste tu ¿me podrías decir otra vez que tengo que revisar? Siento molestarte...

**Comment by nasivuela** [comment]
Ya lo tienes ;)

**Comment by carmenpmoreno** [comment]
Gracias @nasivuela ! Perdona, ayer no vi tu mensaje. He revisado todos los puntos que me comentabas. Tengo una duda: no caigo en qué quieres que haga respecto a los estilos, tengo un css por componente actualmente. Los he metido en componentes en vez de en la carpeta stylesheets. Si puedes, me dices. Gracias!

**Comment by nasivuela** [comment]
Excelente!

![](https://media.giphy.com/media/l41lZxzroU33typuU/giphy.gif)

**Comment by carmenpmoreno** [comment]
gracias!
